### ISSUE TITLE
Disable cache if cookie is set

### ISSUE THREAD

**Issue by sascha1337** [bradoyler/route-cache#21]
Hi, if my user is logged in, i want to disable caching.
This could be done using middleware + cookie in express..
Is this possible using your library?

**Comment by markbrown4** [comment]
It's possible with https://github.com/bradoyler/route-cache/pull/22 but I'd suggest holding off using this package until issues #24 and #25 are resolved.

**Comment by bradoyler** [comment]
Yep, this is possible now via #22.
