### ISSUE TITLE
caching 404's

### ISSUE THREAD

**Issue by markbrown4** [bradoyler/route-cache#23]
We're using `next()` to fall through to 404 and error routes, when we cache both of these routes the request just hangs and never resolves.

```js
// server.js
const express = require('express')
const cache = require('route-cache')

const app = express()
app.route('/test').get(cache.cacheSeconds(5), function (req, res, next) {
  if (req.params.something) {
    // fetch something then
    res.send('Found something')
  } else {
    next()
  }
})
app.route('*').get(cache.cacheSeconds(5), function (req, res) {
  // fetch alternative things then
  res.send('404')
})

console.log('open http://localhost:4567/test')
app.listen(4567)
```

Any ideas for how we can solve this one?
Both routes do fetch data from the server so ideally we can cache both.

**Comment by bradoyler** [comment]
This is really an express question, but avoid using `route('*')`, and add middleware at the very end, like so:

```
app.use(function handle404(req, res) {
    res.status(404).send('404');
  });

  app.use(function handle500(error, req, res, next) {
    res.status(500).send('500')
  })
```

**Comment by bradoyler** [comment]
Also, you don't want to apply routeCache to 404 or Error handlers.

**Comment by markbrown4** [comment]
If the 404 is complex and takes time to build why not cache it to reduce load?

**Comment by bradoyler** [comment]
@markbrown4 well, because route-cache doesn't cache `statusCode < 400` 
In order to support caching within a 404, you'd have to modify the logic @ : https://github.com/bradoyler/route-cache/blob/master/index.js#L70

**Comment by markbrown4** [comment]
Ok, despite my attempts at tinkering I've been unable to get the two routes with caching working.  The send is added to the queue here but never processed.

https://github.com/bradoyler/route-cache/blob/master/index.js#L129

**Comment by markbrown4** [comment]
Success. If I change that line you suggested to cache 404's I don't need to call cacheSeconds in both places.  The `cache.cacheSeconds` falls through to the 404 and I get the desired behavior - caching in both places.

```js
if (res.statusCode < 400 || res.statusCode === 404) {
  cacheStore.set(key, { body: body, isJson: isJson }, ttl)
}
```

```js
// server.js
const express = require('express')
const cache = require('route-cache')

const app = express()
app.route('/test').get(cache.cacheSeconds(5), function (req, res, next) {
  if (req.params.something) {
    res.send('Found something')
  } else {
    next()
  }
})
app.use(function (req, res) {
  console.log('404')
  res.send('404')
})

console.log('open http://localhost:4567/test')
app.listen(4567)
```

**Comment by bradoyler** [comment]
So by definition, a 404 is used to show that the "requested resource can not be found". So I suppose I could be convinced that a 404 should be cacheable. 
I'd just need to make sure the cached response still returns a 404 statusCode.
