### ISSUE TITLE
Status code of all cached responses is 200

### ISSUE THREAD

**Issue by yutak23** [bradoyler/route-cache#56]
I always use this library. Thank you very much.

When I implement the following API, the status code of the response cached by route-cache is 200.
The expected value is to return 204.

```js
app.get('/email/exists', async (req, res) => {
	try {
		const userExists = await getUserByEmail(req.query.email);
		if (userExists) res.status(204).send();

		res.status(404).json({ message: 'User not found' });
	} catch (e) {
		res.status(500).json({ message: e.message });
	}
});
```

**Comment by bradoyler** [comment]
v0.6.1 published https://www.npmjs.com/package/route-cache/v/0.6.1
